project:
  type: website

website:
  title: "NAIA Women's Wrestling Championships"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: placers.qmd
        text: National Placers
      - href: teams.qmd
        text: Team Search
      - href: growth.qmd
        text: Growth
      - href: rosters.qmd
        text: Rosters
      - href: matches.qmd
        text: Match Results

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
