project:
  type: website

website:
  title: "NAIA Women's Wrestling Championships"
  navbar:
    left:
      - href: index.qmd
        text: Statistics
      - href: about.qmd
        text: Website Context

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



